title: Nikolay Lebedev
email: nklbdev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Все права защищены, накормлены и уложены спать.
  Ничего личного, только личный блог.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nklbdev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nklbdev
github_username:  nklbdev
#theme: minima
plugins:
  - jekyll-feed

future: true
exclude:
  licenses
# plugins:
#   - jekyll-paginate
#   - jekyll-gist
#   - redcarpet

# From Hyde

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
tagline:          'Tagline text'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/nklbdev/nklbdev.github.io
